services:
  backend:
    build:
      context: ./backend
    container_name: netflix_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: netflix_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflix
    volumes:
      - netflix_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  netflix_db_data: