# Generated by Django 5.1.5 on 2025-01-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netflixtitle',
            options={'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
    ]
